# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M184IoZ1WKt9o61BU6lAexq2dUzyXVtC

Q.1
"""

import pandas as pd
pd.__version__

"""Q.2"""

import pandas as pd
import numpy as np
# numpy array
arr=np.array(['Nisson','Renault','Ford','Toyota','Hyundai','Suzuki'])
# creating series
s=pd.Series(arr)
print(s)

"""Q.3"""

n=pd.Series(arr,index=['CM 1','CM 2','CM 3','CM 4','CM 5','CM 6'])
print(n)

#index of a series into a column of a dataframe
import pandas as pd
df=pd.DataFrame({'SI.NO':['1','2','3'],'Car Brand':['Nisson','Renault','Ford'],'Branch':['chennai','Mumbai','Hyerabad']})
df

df=pd.DataFrame(n,columns=['companies name'])
df

"""Q.4"""

import seaborn as sns
mpg=sns.load_dataset('mpg')
mpg.head()

"""Q.5"""

mpg=sns.load_dataset('mpg')
df=pd.DataFrame(mpg)
df.origin.unique()

"""Q.6"""

mpg.describe()

mpg['origin'].describe()

mpg['origin'].unique()

mpg['origin'].value_counts()

sns.distplot(mpg['weight']);

sns.pairplot(mpg);

